<script src="<?php echo WEBURL ?>assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.21/filtering/type-based/accent-neutralise.js"></script>
<script src="<?php echo WEBURL; ?>assets/js/form-validation-custom.js"></script>
<script src="<?php echo WEBURL; ?>assets/js/select2/select2.full.min.js"></script>
<script src="<?php echo WEBURL; ?>assets/js/datepicker/date-picker/datepicker.js"></script>
<script src="<?php echo WEBURL; ?>assets/js/datepicker/date-picker/datepicker.en.js"></script>
<script src="<?php echo WEBURL ?>code/js/management.js"></script>